### ISSUE TITLE
Can't smelt any Tech Expansion ore and can't make Crusher without smelting ore

### ISSUE THREAD

**Issue by Dragnier** [abused/Tech-Expansion#11]
There is a catch22 problem here. All of your ores require they be ground before they smelt into ingots, but you can't grind them without making the crusher which requires some of those ingots. Basically, you haven't registered any smelting recipes for the ores.

**Comment by abused** [comment]
Actually im not sure what your talking about? In my dev environment and compiled the mod works just fine, recipes are registered and can be found in the ModRecipes class.

**Comment by Dragnier** [comment]
Hmmm. I guess it could be bad mod interaction with something else. I'll try checking by disabling one at a time. I'll post the results here and to whatever mod is responsible because it could be from either one or specific to the two being together.
