### ISSUE TITLE
[1.11.2] Random Rubber Trees without logs spawning in the Ocean.

### ISSUE THREAD

**Issue by ThomasAunvik** [abused/Tech-Expansion#13]
Tech Expansion version 1.5

While making a new world, and then there were an ocean near me. Then i found there were trees without the logs just floating there. After some time there were ALOT of raw rubber laying in the ground.

Same thing happens over other places.

![Imgur](http://i.imgur.com/PbCtDm2.png)
![Imgur](http://i.imgur.com/xQOlW4l.png)

**Comment by abused** [comment]
Yes im aware of the issue and currently am rewriting the entire mod and fixing every single bug i come across it will be fixed when the rewrite is done
