### ISSUE TITLE
Tinker's Construct integration

### ISSUE THREAD

**Issue by Zeevian** [abused/Tech-Expansion#16]
The harvest level of a tinker's tool is not being received and allowing you to mine the ores.
![2017-05-28_23 04 44](https://cloud.githubusercontent.com/assets/22180382/26535332/3f0109a8-43fa-11e7-9a9b-f25277fa7e8d.png)
No progress is ever made on the block for as long as you are trying to mine.  Attempted to mine for 30s.
![2017-05-28_23 04 36](https://cloud.githubusercontent.com/assets/22180382/26535342/57b8cb3e-43fa-11e7-9804-e086f117da51.png)
If you do mine it with a tinker's tool, you do still acquire the ore.

**Comment by abused** [comment]
Again, right now the mod is going through a full rewrite to make it better, more functional, and fix all the bugs, this one included, please be patient, when the rewrite is done i will upload it on curse
