### ISSUE TITLE
Putting an unsupported item into the pulverizer causes a crash

### ISSUE THREAD

**Issue by vpzomtrrfrt** [abused/Tech-Expansion#2]
http://ix.io/1GmL

**Comment by abused** [comment]
Yup, fully aware of this problem, its going to be fixed on the next commit as i have done a ton of changes that have not been pushed to github yet

**Comment by abused** [comment]
Not really sure how to fix this right now tbh, this and the problem with hoppers not being able to output take stuff out and crash when trying to input stuff through a side

**Comment by DoughnutDev** [comment]
Same thing happens with RF Furnace

**Comment by abused** [comment]
Fixed
