### ISSUE TITLE
needs dumby proofing (techexpansion-1.4)

### ISSUE THREAD

**Issue by SDUBZ** [abused/Tech-Expansion#7]
so i was testing the energy banks and thought how do i charge my jetpack and tried shifticking in the jetpack to the energy bank and it crashed me

TX: techexpansion-1.4
forge:1.11.2-2226
crash report:
[crash-2017-02-02_12.09.24-client.txt](https://github.com/abused/Tech-Expansion/files/746599/crash-2017-02-02_12.09.24-client.txt)

**Comment by abused** [comment]
Working on a fix now

**Comment by SDUBZ** [comment]
can you add a slot to charge jetpack or is there another method coming for that?

**Comment by abused** [comment]
thats being worked on for the Energy Banks

**Comment by abused** [comment]
Fixed and charge slot added, update will be out soon
