### ISSUE TITLE
Issue that stops ability to teleport

### ISSUE THREAD

**Issue by OcAMD** [abused/Tech-Expansion#9]
I was using techexpansion-1.4.jar and when it is in the mods folder you are unable to utilize the tp command or utilize Voxel map to teleport. As soon as this mod is removed the problem is resolved. Sadly this makes me unable to enjoy your mod. Your conduit doesn't work properly either. You only get power to the first conduit unless you make the connection and add and break additional sections to "trick" the connection. Maybe this [link](http://www.minecraftforge.net/forum/topic/26855-rf-pipes/) will give you an idea on how to possibly fix that or where you may look.

I was using the following:
techexpansion-1.4.jar
forge-1.11.2-13.20.0.2227

**Comment by abused** [comment]
Sorry that this is an issue currently and i have found the bug, it will be fixed in the next update, as to the conduits i know well that they are terrible, for now its all on using other mods conduits until i finish everything else and get back to them to retexture them and fix them.

**Comment by abused** [comment]
Fixed will have an update out soon, as for conduits im going to leave those till last as i said earlier
